/**
 * @file zepra-dump-bytecode.cpp
 * @brief Tool for inspecting bytecode
 */

#include <iostream>
#include <string>

#include "zeprascript/config.hpp"
#include "zeprascript/frontend/source_code.hpp"
#include "zeprascript/frontend/lexer.hpp"

using namespace Zepra;

void printUsage() {
    std::cout << "Usage: zepra-dump-bytecode <file.js>\n";
    std::cout << "\n";
    std::cout << "Compiles a JavaScript file and displays the generated bytecode.\n";
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        printUsage();
        return 1;
    }
    
    std::string filename = argv[1];
    
    auto source = Frontend::SourceCode::fromFile(filename);
    if (!source) {
        std::cerr << "Error: Could not read file '" << filename << "'\n";
        return 1;
    }
    
    std::cout << "=== Source: " << filename << " ===\n";
    std::cout << source->content() << "\n";
    std::cout << "\n";
    
    std::cout << "=== Tokens ===\n";
    Frontend::Lexer lexer(source.get());
    while (!lexer.isEof()) {
        Frontend::Token token = lexer.nextToken();
        std::cout << Frontend::Token::typeName(token.type);
        if (!token.value.empty()) {
            std::cout << " '" << token.value << "'";
        }
        std::cout << "\n";
        
        if (token.type == Frontend::TokenType::EndOfFile) {
            break;
        }
    }
    
    std::cout << "\n=== Bytecode ===\n";
    std::cout << "(Bytecode generation not yet implemented)\n";
    
    return 0;
}
